import 'package:adas_development/core/app_export.dart';import 'package:adas_development/widgets/custom_elevated_button.dart';import 'package:adas_development/widgets/custom_icon_button.dart';import 'package:adas_development/widgets/custom_outlined_button.dart';import 'package:adas_development/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';class AttentionTwentyoneScreen extends StatelessWidget {const AttentionTwentyoneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 46.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 32.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomIconButton(height: 56.adaptSize, width: 56.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgClockBlack90002)), Padding(padding: EdgeInsets.only(left: 63.h, top: 4.v, bottom: 15.v), child: Text("Attention", style: theme.textTheme.headlineMedium))]))), SizedBox(height: 50.v), _buildOtpView(context), SizedBox(height: 34.v), Text("Select the numbers in the forward order", style: theme.textTheme.bodyMedium), SizedBox(height: 40.v), _buildOtpViewColumn(context), SizedBox(height: 80.v), _buildTwentyOneButton(context), SizedBox(height: 64.v), _buildDoneButton(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildOtpView(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 132.h), child: CustomPinCodeTextField(context: context, onChanged: (value) {})); } 
/// Section Widget
Widget _buildOtpView1(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 1.h), child: CustomPinCodeTextField(context: context, onChanged: (value) {})); } 
/// Section Widget
Widget _buildOtpViewColumn(BuildContext context) { return Container(margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 78.v), decoration: AppDecoration.fillBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder54), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [_buildOtpView1(context), SizedBox(height: 31.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(width: 60.h, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 5.v), decoration: AppDecoration.fillSecondaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Text("6", style: theme.textTheme.titleLarge)), CustomImageView(imagePath: ImageConstant.imgUserBlack9000245x61, height: 45.v, width: 61.h), Container(width: 60.h, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 5.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Text("8", style: theme.textTheme.titleLarge)), Container(width: 61.h, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 5.v), decoration: AppDecoration.fillSecondaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Text("9", style: theme.textTheme.titleLarge)), Container(width: 61.h, padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 5.v), decoration: AppDecoration.fillSecondaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Text("10", style: theme.textTheme.titleLarge))]))])); } 
/// Section Widget
Widget _buildTwentyOneButton(BuildContext context) { return CustomOutlinedButton(text: "2,1,8,5,4", margin: EdgeInsets.only(left: 27.h, right: 26.h)); } 
/// Section Widget
Widget _buildDoneButton(BuildContext context) { return CustomElevatedButton(width: 146.h, text: "Done", onPressed: () {onTapDoneButton(context);}); } 
/// Navigates to the attentionTwentyScreen when the action is triggered.
onTapDoneButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.attentionTwentyScreen); } 
 }
